### ISSUE TITLE
Fix ConcurrentModificationException

### ISSUE THREAD

**Issue by chaoran-chen** [loculus-project/loculus#1623]
In tests, we regularly see a "ConcurrentModificationException". We should investigate whether it is only a test-related problem or whether we are also making problematic, concurrent access during production.

Example for a failed test: https://github.com/loculus-project/loculus/actions/runs/8742032676/job/23989393379

<details>
<summary>Full error stack trace</summary>

```
SubmitProcessedDataEndpointTest > GIVEN invalid processed data THEN refuses to update and an error will be thrown(InvalidDataScenario) > GIVEN data with segment in aligned nucleotide sequences of wrong length THEN the response contains The length of 'main' in 'alignedNucleotideSequences' is 123, but it should be 49. FAILED
    java.util.ConcurrentModificationException
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1229)
        at org.springframework.util.LinkedCaseInsensitiveMap.computeIfAbsent(LinkedCaseInsensitiveMap.java:239)
        at org.springframework.util.LinkedCaseInsensitiveMap.computeIfAbsent(LinkedCaseInsensitiveMap.java:50)
        at org.springframework.mock.web.MockHttpServletResponse.doAddHeaderValue(MockHttpServletResponse.java:753)
        at org.springframework.mock.web.MockHttpServletResponse.addHeaderValue(MockHttpServletResponse.java:711)
        at org.springframework.mock.web.MockHttpServletResponse.addHeader(MockHttpServletResponse.java:679)
        at jakarta.servlet.http.HttpServletResponseWrapper.addHeader(HttpServletResponseWrapper.java:141)
        at org.springframework.security.web.firewall.FirewalledResponse.addHeader(FirewalledResponse.java:60)
        at jakarta.servlet.http.HttpServletResponseWrapper.addHeader(HttpServletResponseWrapper.java:141)
        at org.springframework.security.web.header.writers.StaticHeadersWriter.writeHeaders(StaticHeadersWriter.java:64)
        at org.springframework.security.web.header.HeaderWriterFilter.writeHeaders(HeaderWriterFilter.java:99)
        at org.springframework.security.web.header.HeaderWriterFilter$HeaderWriterResponse.writeHeaders(HeaderWriterFilter.java:132)
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:93)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
        at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82)
        at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
        at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
        at org.springframework.security.web.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$0(ObservationFilterChainDecorator.java:323)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:224)
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191)
        at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113)
        at org.springframework.web.servlet.handler.HandlerMappingIntrospector.lambda$createCacheFilter$3(HandlerMappingIntrospector.java:195)
        at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113)
        at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74)
        at org.springframework.security.config.annotation.web.configuration.WebMvcSecurityConfiguration$CompositeFilterChainProxy.doFilter(WebMvcSecurityConfiguration.java:230)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
        at org.springframework.test.web.servlet.setup.MockMvcFilterDecorator.doFilter(MockMvcFilterDecorator.java:151)
        at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:132)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.springframework.test.web.servlet.setup.MockMvcFilterDecorator.doFilter(MockMvcFilterDecorator.java:151)
        at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:132)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.springframework.test.web.servlet.setup.MockMvcFilterDecorator.doFilter(MockMvcFilterDecorator.java:151)
        at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:132)
        at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.springframework.test.web.servlet.setup.MockMvcFilterDecorator.doFilter(MockMvcFilterDecorator.java:151)
        at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:132)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.springframework.test.web.servlet.setup.MockMvcFilterDecorator.doFilter(MockMvcFilterDecorator.java:151)
        at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:132)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:[101](https://github.com/loculus-project/loculus/actions/runs/8742032676/job/23989393379#step:4:104))
        at org.springframework.test.web.servlet.setup.MockMvcFilterDecorator.doFilter(MockMvcFilterDecorator.java:151)
        at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:132)
        at org.springframework.test.web.servlet.MockMvc.perform(MockMvc.java:201)
        at org.loculus.backend.controller.submission.SubmissionControllerClient.extractUnprocessedData(SubmissionControllerClient.kt:60)
        at org.loculus.backend.controller.submission.SubmissionControllerClient.extractUnprocessedData$default(SubmissionControllerClient.kt:55)
        at org.loculus.backend.controller.submission.SubmissionConvenienceClient.extractUnprocessedData(SubmissionConvenienceClient.kt:207)
        at org.loculus.backend.controller.submission.SubmissionConvenienceClient.extractUnprocessedData$default(SubmissionConvenienceClient.kt:203)
        at org.loculus.backend.controller.submission.SubmitProcessedDataEndpointTest.prepareExtractedSequencesInDatabase(SubmitProcessedDataEndpointTest.kt:430)
        at org.loculus.backend.controller.submission.SubmitProcessedDataEndpointTest.prepareExtractedSequencesInDatabase$default(SubmitProcessedDataEndpointTest.kt:425)
        at org.loculus.backend.controller.submission.SubmitProcessedDataEndpointTest.GIVEN invalid processed data THEN refuses to update and an error will be thrown(SubmitProcessedDataEndpointTest.kt:264)
```

</details>

**Comment by chaoran-chen** [comment]
I haven't seen this in a long time, so I'm closing this.
