### ISSUE TITLE
Website stalls when authentication not ready

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#2221]
When authentication isn't up, the website seems to either stall, crash or become unhealthy in the eyes of kubernetes.

We have a quite long timeout for the call to authentication, maybe it's enough to reduce it to something more like 500ms to prevent long latency.

Example error stacktrace:

```
{"instance":"LoginMiddleware","level":"error","message":"Error discovering keycloak issuer: RPError: outgoing request timed out after 3500ms","timestamp":"2024-07-01T13:16:34.241Z"}
13:16:34 [ERROR] RPError: outgoing request timed out after 3500ms
    at /app/node_modules/openid-client/lib/helpers/request.js:140:13
    at async Issuer.discover (/app/node_modules/openid-client/lib/issuer.js:143:22)
    at async KeycloakClientManager.getClient (file:///app/dist/server/chunks/getAuthUrl_B0oU3BjW.mjs:35:30)
    at async file:///app/dist/server/chunks/authMiddleware_CC8PDQtr.mjs:72:18
    at async callMiddleware (file:///app/dist/server/entry.mjs:490:10)
    at async RenderContext.render (file:///app/dist/server/entry.mjs:1076:22)
    at async NodeApp.render (file:///app/dist/server/entry.mjs:1837:18)
    at async file:///app/dist/server/entry.mjs:2172:24
```

We should probably also downgrade some log messages from error to warn: it can happen that lapis/auth is down, it's not something the website can do anything about.

```
{"instance":"lapisClient","level":"error","message":"Unknown error from LAPIS: {\"message\":\"connect ECONNREFUSED 10.43.222.252:8080\",\"name\":\"Error\",\"stack\":\"Error: connect ECONNREFUSED 10.43.222.252:8080\\n    at AxiosError.from (file:///app/node_modules/axios/lib/core/AxiosError.js:89:14)\\n    at RedirectableRequest.handleRequestError (file:///app/node_modules/axios/lib/adapters/http.js:610:25)\\n    at RedirectableRequest.emit (node:events:520:28)\\n    at eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:38:24)\\n    at ClientRequest.emit (node:events:520:28)\\n    at Socket.socketErrorListener (node:_http_client:502:9)\\n    at Socket.emit (node:events:520:28)\\n    at emitErrorNT (node:internal/streams/destroy:170:8)\\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\\n    at Axios.request (file:///app/node_modules/axios/lib/core/Axios.js:45:41)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async B.request (file:///app/node_modules/@zodios/core/lib/index.mjs:9:6356)\\n    at async getTotalAndLastUpdatedAt (file:///app/dist/server/chunks/index_C0PpPvBs.mjs:87:11)\",\"config\":{\"transitional\":{\"silentJSONParsing\":true,\"forcedJSONParsing\":true,\"clarifyTimeoutError\":false},\"adapter\":[\"xhr\",\"http\",\"fetch\"],\"transformRequest\":[null],\"transformResponse\":[null],\"timeout\":0,\"xsrfCookieName\":\"XSRF-TOKEN\",\"xsrfHeaderName\":\"X-XSRF-TOKEN\",\"maxContentLength\":-1,\"maxBodyLength\":-1,\"env\":{},\"headers\":{\"Accept\":\"application/json, text/plain, */*\",\"Content-Type\":\"application/json\",\"User-Agent\":\"axios/1.7.2\",\"Content-Length\":\"13\",\"Accept-Encoding\":\"gzip, compress, deflate, br\"},\"baseURL\":\"http://loculus-lapis-service-cchf:8080\",\"method\":\"post\",\"url\":\"/sample/aggregated\",\"data\":\"{\\\"version\\\":1}\",\"params\":{}},\"code\":\"ECONNREFUSED\",\"status\":null}","timestamp":"2024-07-01T13:16:47.536Z"}
{"instance":"LoginMiddleware","level":"warn","message":"Connection refused when trying to discover the keycloak issuer at url: http://loculus-keycloak-service:8083/realms/loculus","timestamp":"2024-07-01T13:16:48.303Z"}
{"instance":"LoginMiddleware","level":"error","message":"Error discovering keycloak issuer: RPError: outgoing request timed out after 3500ms","timestamp":"2024-07-01T13:16:48.748Z"}
{"instance":"LoginMiddleware","level":"warn","message":"Connection refused when trying to discover the keycloak issuer at url: http://loculus-keycloak-service:8083/realms/loculus","timestamp":"2024-07-01T13:16:49.328Z"}
{"instance":"LoginMiddleware","level":"info","message":"Getting keycloak client for issuer url: http://loculus-keycloak-service:8083/realms/loculus","timestamp":"2024-07-01T13:16:49.739Z"}
{"instance":"LoginMiddleware","level":"warn","message":"Connection refused when trying to discover the keycloak issuer at url: http://loculus-keycloak-service:8083/realms/loculus","timestamp":"2024-07-01T13:16:50.799Z"}
{"instance":"LoginMiddleware","level":"warn","message":"Keycloak client not available, pretending user logged out","timestamp":"2024-07-01T13:16:50.800Z"}
{"instance":"LoginMiddleware","level":"info","message":"Getting keycloak client for issuer url: http://loculus-keycloak-service:8083/realms/loculus","timestamp":"2024-07-01T13:16:51.306Z"}
{"instance":"LoginMiddleware","level":"warn","message":"Connection refused when trying to discover the keycloak issuer at url: http://loculus-keycloak-service:8083/realms/loculus","timestamp":"2024-07-01T13:16:51.308Z"}
{"instance":"lapisClient","level":"error","message":"Unknown error from LAPIS: {\"message\":\"connect ECONNREFUSED 10.43.222.252:8080\",\"name\":\"Error\",\"stack\":\"Error: connect ECONNREFUSED 10.43.222.252:8080\\n    at AxiosError.from (file:///app/node_modules/axios/lib/core/AxiosError.js:89:14)\\n    at RedirectableRequest.handleRequestError (file:///app/node_modules/axios/lib/adapters/http.js:610:25)\\n    at RedirectableRequest.emit (node:events:520:28)\\n    at eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:38:24)\\n    at ClientRequest.emit (node:events:520:28)\\n    at Socket.socketErrorListener (node:_http_client:502:9)\\n    at Socket.emit (node:events:520:28)\\n    at emitErrorNT (node:internal/streams/destroy:170:8)\\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\\n    at Axios.request (file:///app/node_modules/axios/lib/core/Axios.js:45:41)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async B.request (file:///app/node_modules/@zodios/core/lib/index.mjs:9:6356)\\n    at async getTotalAndLastUpdatedAt (file:///app/dist/server/chunks/index_C0PpPvBs.mjs:87:11)\",\"config\":{\"transitional\":{\"silentJSONParsing\":true,\"forcedJSONParsing\":true,\"clarifyTimeoutError\":false},\"adapter\":[\"xhr\",\"http\",\"fetch\"],\"transformRequest\":[null],\"transformResponse\":[null],\"timeout\":0,\"xsrfCookieName\":\"XSRF-TOKEN\",\"xsrfHeaderName\":\"X-XSRF-TOKEN\",\"maxContentLength\":-1,\"maxBodyLength\":-1,\"env\":{},\"headers\":{\"Accept\":\"application/json, text/plain, */*\",\"Content-Type\":\"application/json\",\"User-Agent\":\"axios/1.7.2\",\"Content-Length\":\"13\",\"Accept-Encoding\":\"gzip, compress, deflate, br\"},\"baseURL\":\"http://loculus-lapis-service-cchf:8080\",\"method\":\"post\",\"url\":\"/sample/aggregated\",\"data\":\"{\\\"version\\\":1}\",\"params\":{}},\"code\":\"ECONNREFUSED\",\"status\":null}","timestamp":"2024-07-01T13:16:52.848Z"}
{"instance":"lapisClient","level":"error","message":"Unknown error from LAPIS: {\"message\":\"connect ECONNREFUSED 10.43.206.90:8080\",\"name\":\"Error\",\"stack\":\"Error: connect ECONNREFUSED 10.43.206.90:8080\\n    at AxiosError.from (file:///app/node_modules/axios/lib/core/AxiosError.js:89:14)\\n    at RedirectableRequest.handleRequestError (file:///app/node_modules/axios/lib/adapters/http.js:610:25)\\n    at RedirectableRequest.emit (node:events:520:28)\\n    at eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:38:24)\\n    at ClientRequest.emit (node:events:520:28)\\n    at Socket.socketErrorListener (node:_http_client:502:9)\\n    at Socket.emit (node:events:520:28)\\n    at emitErrorNT (node:internal/streams/destroy:170:8)\\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\\n    at Axios.request (file:///app/node_modules/axios/lib/core/Axios.js:45:41)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async B.request (file:///app/node_modules/@zodios/core/lib/index.mjs:9:6356)\\n    at async getRecent (file:///app/dist/server/chunks/index_C0PpPvBs.mjs:102:11)\",\"config\":{\"transitional\":{\"silentJSONParsing\":true,\"forcedJSONParsing\":true,\"clarifyTimeoutError\":false},\"adapter\":[\"xhr\",\"http\",\"fetch\"],\"transformRequest\":[null],\"transformResponse\":[null],\"timeout\":0,\"xsrfCookieName\":\"XSRF-TOKEN\",\"xsrfHeaderName\":\"X-XSRF-TOKEN\",\"maxContentLength\":-1,\"maxBodyLength\":-1,\"env\":{},\"headers\":{\"Accept\":\"application/json, text/plain, */*\",\"Content-Type\":\"application/json\",\"User-Agent\":\"axios/1.7.2\",\"Content-Length\":\"41\",\"Accept-Encoding\":\"gzip, compress, deflate, br\"},\"baseURL\":\"http://loculus-lapis-service-west-nile:8080\",\"method\":\"post\",\"url\":\"/sample/aggregated\",\"data\":\"{\\\"releasedAtFrom\\\":1717247810,\\\"version\\\":1}\",\"params\":{}},\"code\":\"ECONNREFUSED\",\"status\":null}","timestamp":"2024-07-01T13:16:53.873Z"}
{"instance":"lapisClient","level":"error","message":"Unknown error from LAPIS: {\"message\":\"connect ECONNREFUSED 10.43.65.138:8080\",\"name\":\"Error\",\"stack\":\"Error: connect ECONNREFUSED 10.43.65.138:8080\\n    at AxiosError.from (file:///app/node_modules/axios/lib/core/AxiosError.js:89:14)\\n    at RedirectableRequest.handleRequestError (file:///app/node_modules/axios/lib/adapters/http.js:610:25)\\n    at RedirectableRequest.emit (node:events:520:28)\\n    at eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:38:24)\\n    at ClientRequest.emit (node:events:520:28)\\n    at Socket.socketErrorListener (node:_http_client:502:9)\\n    at Socket.emit (node:events:520:28)\\n    at emitErrorNT (node:internal/streams/destroy:170:8)\\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\\n    at Axios.request (file:///app/node_modules/axios/lib/core/Axios.js:45:41)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async B.request (file:///app/node_modules/@zodios/core/lib/index.mjs:9:6356)\\n    at async getTotalAndLastUpdatedAt (file:///app/dist/server/chunks/index_C0PpPvBs.mjs:87:11)\",\"config\":{\"transitional\":{\"silentJSONParsing\":true,\"forcedJSONParsing\":true,\"clarifyTimeoutError\":false},\"adapter\":[\"xhr\",\"http\",\"fetch\"],\"transformRequest\":[null],\"transformResponse\":[null],\"timeout\":0,\"xsrfCookieName\":\"XSRF-TOKEN\",\"xsrfHeaderName\":\"X-XSRF-TOKEN\",\"maxContentLength\":-1,\"maxBodyLength\":-1,\"env\":{},\"headers\":{\"Accept\":\"application/json, text/plain, */*\",\"Content-Type\":\"application/json\",\"User-Agent\":\"axios/1.7.2\",\"Content-Length\":\"13\",\"Accept-Encoding\":\"gzip, compress, deflate, br\"},\"baseURL\":\"http://loculus-lapis-service-dummy-organism:8080\",\"method\":\"post\",\"url\":\"/sample/aggregated\",\"data\":\"{\\\"version\\\":1}\",\"params\":{}},\"code\":\"ECONNREFUSED\",\"status\":null}","timestamp":"2024-07-01T13:16:54.704Z"}
```

**Comment by theosanderson** [comment]
Closing as desired behaviour - feel free to reopen if you disagree
