### ISSUE TITLE
ena-submission: Better logging of webin-cli errors

### ISSUE THREAD

**Issue by anna-parker** [loculus-project/loculus#2840]
I add all errors to the DB, however ENA often does not write error details into logs but into a temp file, we should read the error from there before writing this to the logs - this isn't easy as often  multiple files are created and depending on the error the file will be named differently.
```
INFO : Creating report file: /tmp/./webin-cli.report
ERROR: Submission validation failed because of a user error. Manifest name : LOC_000RBUH2024-09-18_16_50_54.485245_00_00. See reports for details : /tmp/genome/LOC_000RBUH2024-09-18_16_50_54.485245_00_00/validate. All information is available in the output directory : /tmp
, Stderr: uk.ac.ebi.embl.api.validation.ValidationEngineException: fasta file validation failed : tmpr7_ooilv.fasta.gz, Please see the error report: /tmp/genome/LOC_000RBUH2024-09-18_16_50_54.485245_00_00/validate/tmpr7_ooilv.fasta.gz.report
	at uk.ac.ebi.embl.api.validation.submission.SubmissionValidationPlan.throwValidationCheckException(SubmissionValidationPlan.java:381)
	at uk.ac.ebi.embl.api.validation.submission.SubmissionValidationPlan.validateFasta(SubmissionValidationPlan.java:221)
	at uk.ac.ebi.embl.api.validation.submission.SubmissionValidationPlan.execute(SubmissionValidationPlan.java:84)
	at uk.ac.ebi.embl.api.validation.submission.SubmissionValidator.validate(SubmissionValidator.java:62)
	at uk.ac.ebi.embl.api.validation.submission.SubmissionValidator.validate(SubmissionValidator.java:89)
	at uk.ac.ebi.ena.webin.cli.WebinCliExecutor.validateSubmission(WebinCliExecutor.java:138)
	at uk.ac.ebi.ena.webin.cli.WebinCli.validate(WebinCli.java:317)
	at uk.ac.ebi.ena.webin.cli.WebinCli.execute(WebinCli.java:286)
	at uk.ac.ebi.ena.webin.cli.WebinCli.__main(WebinCli.java:122)
	at uk.ac.ebi.ena.webin.cli.WebinCli.main(WebinCli.java:90)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
```

**Comment by anna-parker** [comment]
I now read all the files and log their contents! its a bit ugly but we dont loose any error messages anymore!
