### ISSUE TITLE
Flaky backend test with wrong assumptions about ordering

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#3242]
Yet another test that expects exact ordering when we don't actually promise this (we could order in SQL but we don't):

```
ApproveProcessedDataEndpointTest > WHEN user approves with submitterNamesFilter THEN only approves entries from submitter in filter() FAILED
    java.lang.AssertionError: JSON path "$[*].accession" expected:<[LOC_000001Y, LOC_000002W, LOC_000003U, LOC_000004S, LOC_000005Q, LOC_000006N, LOC_000007L, LOC_000008J, LOC_000009G, LOC_00000AE]> but was:<["LOC_000006N","LOC_000004S","LOC_000007L","LOC_000003U","LOC_000009G","LOC_000002W","LOC_000008J","LOC_000005Q","LOC_00000AE","LOC_000001Y"]>
        at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:59)
        at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:122)
        at org.springframework.test.util.JsonPathExpectationsHelper.assertValue(JsonPathExpectationsHelper.java:123)
        at org.springframework.test.web.servlet.result.JsonPathResultMatchers.lambda$value$2(JsonPathResultMatchers.java:111)
        at org.springframework.test.web.servlet.MockMvc$1.andExpect(MockMvc.java:214)
        at org.loculus.backend.controller.submission.ApproveProcessedDataEndpointTest.WHEN user approves with submitterNamesFilter THEN only approves entries from submitter in filter(ApproveProcessedDataEndpointTest.kt:383)
```

**Comment by corneliusroemer** [comment]
My computer is too fast detecting all these race conditions it seems ;)

```
DeleteSequencesEndpointTest > WHEN superuser deletes all entries THEN is successfully deleted() FAILED
    java.lang.AssertionError: JSON path "$[0].accession" expected:<LOC_000001Y> but was:<LOC_000006N>
        at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:59)
        at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:122)
        at org.springframework.test.util.JsonPathExpectationsHelper.assertValue(JsonPathExpectationsHelper.java:123)
        at org.springframework.test.web.servlet.result.JsonPathResultMatchers.lambda$value$2(JsonPathResultMatchers.java:111)
        at org.springframework.test.web.servlet.MockMvc$1.andExpect(MockMvc.java:214)
        at org.loculus.backend.controller.submission.DeleteSequencesEndpointTest.WHEN superuser deletes all entries THEN is successfully deleted(DeleteSequencesEndpointTest.kt:303)
```
